SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /u01/app/oracle/admin/PRRBT/scripts/CreateDB.log append
startup nomount pfile="/u01/app/oracle/admin/PRRBT/scripts/init.ora";
CREATE DATABASE "rbt"
MAXINSTANCES 8
MAXLOGHISTORY 1
MAXLOGFILES 32
MAXLOGMEMBERS 3
MAXDATAFILES 500
DATAFILE '+CONS_DATA/PRRBT/datafile/system' SIZE 10G AUTOEXTEND ON NEXT  10M MAXSIZE 32G
EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE '+CONS_DATA/PRRBT/datafile/sysaux' SIZE 1G AUTOEXTEND ON NEXT  10M MAXSIZE 32G
SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '+CONS_DATA/PRRBT/tempfile/temp01'  SIZE 4G AUTOEXTEND ON NEXT  640K MAXSIZE 4G
SMALLFILE UNDO TABLESPACE "UNDOTBS1" DATAFILE '+CONS_DATA/PRRBT/datafile/undo01'  SIZE 4G AUTOEXTEND ON NEXT  5M MAXSIZE 10G
CHARACTER SET CL8MSWIN1251
NATIONAL CHARACTER SET AL16UTF16
SET DEFAULT BIGFILE TABLESPACE 
LOGFILE GROUP 1 ('+CONS_DATA/PRRBT/onlinelog/redo01') SIZE 524288000,
GROUP 2 ('+CONS_DATA/PRRBT/onlinelog/redo02') SIZE 524288000,
GROUP 3 ('+CONS_DATA/PRRBT/onlinelog/redo03') SIZE 524288000
USER SYS IDENTIFIED BY "&&sysPassword" USER SYSTEM IDENTIFIED BY "&&systemPassword";
spool off
