select * from V$GOLDENGATE_CAPTURE
select * from V$GG_APPLY_RECEIVER
select * from V$GG_APPLY_READER
select * from V$GG_APPLY_COORDINATOR
select * from V$GG_APPLY_SERVER
select * from V$GOLDENGATE_TABLE_STATS
select * from V$GOLDENGATE_CAPABILITIES
select * from DBA_APPLY_ERROR
--Configuration Views
select * from DBA_GOLDENGATE_PRIVILEGES
select * from DBA_GOLDENGATE_SUPPORT_MODE
select * from DBA_CAPTURE
select * from DBA_CAPTURE_PARAMETERS
select * from DBA_GOLDENGATE_INBOUND
select * from DBA_GG_INBOUND_PROGRESS
select * from DBA_APPLY
select * from DBA_APPLY_PARAMETERS
select * from DBA_APPLY_REPERROR_HANDLERS
select * from DBA_APPLY_HANDLE_COLLISIONS
select * from DBA_APPLY_DML_CONF_HANDLERS
