

alter index INTERACTIVETAILS2.indx$param$edate invisible;-- ћожет понадобитьс€
alter index INTERACTIVETAILS2.indx$param$h invisible;--
alter index INTERACTIVETAILS2.indx$param$level$five invisible;--
alter index INTERACTIVETAILS2.indx$param$level$four invisible;--
alter index INTERACTIVETAILS2.indx$param$level$one invisible;--
alter index INTERACTIVETAILS2.indx$param$level$three invisible;--
alter index INTERACTIVETAILS2.indx$param$level$two invisible;--
alter index INTERACTIVETAILS2.indx$param$sdate invisible;-- ћожет понадобитьс€
alter index INTERACTIVETAILS2.indx$param$tree invisible;--

select 'drop indexes INTERACTIVETAILS2.'||index_name||';' from dba_indexes i where i.VISIBILITY='INVISIBLE' and owner='INTERACTIVETAILS2'


-- останетс€ один индекс INDX$PARAM$SS on INTERACTIVETAILS2.PARAM (SS_ID)
alter table INTERACTIVETAILS2.param disable constraints PARAM$SS;

--alter table INTERACTIVETAILS2.param enable novalidate constraints PARAM$SS;
-- смотреть на запрос 1pxaq3f1fdjan

select * from dba_users where username='INTERACTIVETAILS2'

INTERACTIVETAILS2.param

select * from dba_constraints where table_name='PARAM' and owner='INTERACTIVETAILS2'
select * from dba_objects where owner='INTERACTIVETAILS2' and status<>'VALID'
select * from dba_indexes where owner='INTERACTIVETAILS2' and table_name='PARAM'




CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$EDATE ON INTERACTIVETAILS2.PARAM(EDATE) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$H ON INTERACTIVETAILS2.PARAM(HISTORICITY) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$LEVEL$FIVE ON INTERACTIVETAILS2.PARAM (LEVEL_FIVE) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$LEVEL$FOUR ON INTERACTIVETAILS2.PARAM (LEVEL_FOUR) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$LEVEL$ONE ON INTERACTIVETAILS2.PARAM (LEVEL_ONE) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$LEVEL$THREE ON INTERACTIVETAILS2.PARAM (LEVEL_THREE) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$LEVEL$TWO ON INTERACTIVETAILS2.PARAM (LEVEL_TWO) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$SDATE ON INTERACTIVETAILS2.PARAM (SDATE) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
CREATE INDEX INTERACTIVETAILS2.INDX$PARAM$TREE ON INTERACTIVETAILS2.PARAM (TREE_LEFT, TREE_RIGHT) TABLESPACE INTERACTIVETAILS2_TBS PARALLEL 10 ONLINE;
