-- Чем занята область
SELECT * FROM V$FLASH_RECOVERY_AREA_USAGE fb;

-- Занятое место
SELECT ROUND((SPACE_USED - SPACE_RECLAIMABLE) / SPACE_LIMIT * 100, 1) AS PERCENT_FULL FROM V$RECOVERY_FILE_DEST;
